spring.application.name=recom

app.jwt.secret=???-??????-???????-32-???????-???????-123456
app.jwt.expiration=3600000

    spring.datasource.url = jdbc:postgresql://localhost:5432/recom
spring.datasource.username = postgres
spring.datasource.password = 123

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update
#spring.jpa.hibernate.ddl-auto = create-drop

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

spring.jpa.open-in-view=false

spring.h2.console.enabled=true

data.movies.file=src/main/resources/data/tmdb_5000_movies.csv
data.credits.file=src/main/resources/data/tmdb_5000_credits.csv

spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.deserialization.READ_UNKNOWN_ENUM_VALUES_AS_NULL=true

spring.thymeleaf.enabled=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

